from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import HexColor


def generate_pdf(report, filename="ResumeIQ_Report.pdf"):

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    title = styles["Title"]
    title.alignment = TA_CENTER
    title.textColor = HexColor("#4F46E5")

    heading = styles["Heading2"]
    heading.textColor = HexColor("#2563eb")

    normal = styles["BodyText"]

    elements = []

    # ---------------- Title ---------------- #

    elements.append(
        Paragraph("ResumeIQ AI Report", title)
    )

    elements.append(
        Paragraph("AI Powered Resume Analysis", normal)
    )

    elements.append(Spacer(1,20))

    # ---------------- Candidate ---------------- #

    elements.append(
        Paragraph("Candidate Information", heading)
    )

    elements.append(
        Paragraph(f"<b>Name:</b> {report['Name']}", normal)
    )

    elements.append(
        Paragraph(f"<b>Email:</b> {report['Email']}", normal)
    )

    elements.append(
        Paragraph(f"<b>Phone:</b> {report['Phone']}", normal)
    )

    elements.append(
        Paragraph(f"<b>GitHub:</b> {report['GitHub']}", normal)
    )

    elements.append(Spacer(1,20))

    # ---------------- ATS ---------------- #

    elements.append(
        Paragraph("ATS Analysis", heading)
    )

    elements.append(
        Paragraph(
            f"<b>ATS Score:</b> {report['ATS Score']}%",
            normal
        )
    )

    elements.append(Spacer(1,20))

    # ---------------- Skills ---------------- #

    elements.append(
        Paragraph("Resume Skills", heading)
    )

    elements.append(
        Paragraph(", ".join(report["Resume Skills"]), normal)
    )

    elements.append(Spacer(1,15))

    elements.append(
        Paragraph("Job Description Skills", heading)
    )

    elements.append(
        Paragraph(", ".join(report["JD Skills"]), normal)
    )

    elements.append(Spacer(1,15))

    elements.append(
        Paragraph("Matched Skills", heading)
    )

    elements.append(
        Paragraph(", ".join(report["Matched Skills"]), normal)
    )

    elements.append(Spacer(1,15))

    elements.append(
        Paragraph("Missing Skills", heading)
    )

    elements.append(
        Paragraph(", ".join(report["Missing Skills"]), normal)
    )

    elements.append(Spacer(1,20))

    # ---------------- AI Suggestions ---------------- #

    elements.append(
        Paragraph("AI Suggestions", heading)
    )

    for suggestion in report["AI Suggestions"]:

        elements.append(
            Paragraph(f"• {suggestion}", normal)
        )

    elements.append(Spacer(1,30))

    elements.append(
        Paragraph("Report Information", heading)
    )
    elements.append(
        Paragraph(
            f"<b>Generated On:</b> {report['Generated On']}",
            normal
        )
    )
    elements.append(Spacer(1,30))

    # ---------------- Footer ---------------- #

    elements.append(
        Paragraph(
            "<b>Generated by ResumeIQ AI</b>",
            title
        )
    )

    doc.build(elements)

    return filename