KNOWN_SKILLS = [
    "Python",
    "Java",
    "C",
    "C++",
    "R",
    "SQL",
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "Angular",
    "Vue",
    "Node.js",
    "Express",
    "Flask",
    "Django",
    "Spring Boot",
    "Machine Learning",
    "Deep Learning",
    "Artificial Intelligence",
    "Generative AI",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Git",
    "GitHub",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "GCP",
    "MongoDB",
    "MySQL",
    "PostgreSQL",
    "Pandas",
    "NumPy",
    "Excel",
    "Power BI",
    "Linux"
]